---
title: "Network Analysis"
author: "Ethan Tenison"
date: "8/18/2020"
output: html_document
---

```{r adjacency_matrix, include=FALSE}
library(readr)
library(caret)
library(readxl)
library(igraph)
library(mltools)
library(dummies)
library(dplyr)
library(ggraph)
library(tidygraph)
set.seed(34)


augmented_na <-
  read_csv("data/augmented_networkanalysis_summer2020.csv")
augmented_na$Initiative <- as.factor(augmented_na$Initiative)
augmented_na <- as.data.frame(augmented_na)

# Hot coding the organization variable and creating a
augmented_na <-
  dummy.data.frame(augmented_na, names = c("Initiative"), sep = "_")


# Organization that participate in multiple programs have their rows added together.
library(plyr)
augmented_na <- ddply(augmented_na, "ORGANIZATION", numcolwise(sum))
augmented_na$RGK_center <-
  augmented_na$`Initiative_RGK Course - Consulting for Social Impact` +
  augmented_na$`Initiative_RGK Course - Data Management & Research Life Cycle` +
  augmented_na$`Initiative_RGK Course - Program Evaluation for Nonprofit, Public, & Social Impact Initiatives` +
  augmented_na$`Initiative_RGK Course - Social Impact Case Program`

augmented_na$Good_Measure <-
  augmented_na$`Initiative_Good Measure - Data Leaders Academy` +
  augmented_na$`Initiative_Good Measure - Measuring What Matters`

augmented_na$Mission_Capital <-
  augmented_na$`Initiative_Mission Capital - Data Intelligence` +
  augmented_na$`Initiative_Mission Capital - Leadership Development` +
  augmented_na$`Initiative_Mission Capital - Smart Operations`

augmented_na <-
  dplyr::select(
    augmented_na,
    ORGANIZATION,
    `Initiative_Austin Together Fund`,
    `Initiative_Learn All the Time`,
    `Initiative_Mission Squared`,
    `Initiative_RGK CONNECT Program`,
    RGK_center,
    Good_Measure,
    Mission_Capital
  )


augmented_na <- as.matrix(augmented_na)
rownames(augmented_na) <- augmented_na[, 1]
augmented_na <- augmented_na[,-1]


colnames(augmented_na) <-
  c(
    "Austin Together Fund",
    "Learn All the Time",
    "Mission Squared",
    "CONNECT Program",
    "RGK Center",
    "Good Measure",
    "Mission Capital"
  )

#Program Colors
program_colors <- c("#efb346",
                    "#e8351e",
                    "#cd023d",
                    "#852f88",
                    "#4e54ac",
                    "#0f8096",
                    "#17a769")

names(program_colors) <- c(
  "CONNECT Program",
  "RGK Center",
  "Mission Squared",
  "Austin Together Fund",
  "Learn All the Time",
  "Mission Capital",
  "Good Measure"
)

# number of nonprofits to display
number_of_nonprofits <- 214

```


```{r, build_graph}
# Create igraph object from adjacency matrix than convert to edges
set.seed(34)
g <- graph_from_incidence_matrix(augmented_na, weighted = T)

names <- V(g)$name
de <- degree(g)
st <- graph.strength(g)
be <- betweenness(g, normalized = T)
cl <- closeness(g, mode="all")


# assemble dataset
d <- data.frame(node.name = names, degree = de, strength = st, betweenness = be, closeness=cl)
rownames(d) <- NULL
write.csv(d, "data/centrality.csv")

#Edges
edges <- as.data.frame(get.edgelist(g))

edges1 <-
  edges %>% dplyr::rename(To = V1, From = V2) %>% mutate(Partnerships = 1) %>% dplyr::select(From, To, Partnerships)
set.seed(34)
rows <- sample(nrow(edges1))
vertices1 <- edges1[rows, ]
vertices1 <- distinct(vertices1, To, .keep_all = TRUE)
main_edges <-
  vertices1 %>%  mutate(Main = TRUE) %>% dplyr::select(From, To, Main)
edges1 <-
  edges1 %>% left_join(main_edges, by = c("From", "To")) %>% mutate(Main = replace_na(Main, FALSE))
nonprofit_number <- count(edges1, "To")

edges2 <-
  edges1 %>% count("From") %>% dplyr::rename(To = From, Partnerships = freq) %>% mutate(From = "", Main = TRUE)

edges <- dplyr::bind_rows(edges1, edges2)



#Vertices

vertices1 <-
  vertices1 %>% dplyr::select(From, To) %>% left_join(nonprofit_number, by = "To") %>% transmute(
    Node = To,
    Program = From,
    Partnerships = freq,
    level = 1
  )

vertices1$Program[vertices1$Node == "Learn All The Time"] <- "Austin Together Fund"
vertices1$Program[vertices1$Node == "YouthWorks"] <- "Mission Capital"
vertices1$Program[vertices1$Node == "Capital IDEA"] <- "Good Measure"
vertices1$Program[vertices1$Node == "WFS"] <- "Mission Squared"
vertices1$Program[vertices1$Node == "THN"] <- "RGK Center"

vertices2 <- edges2 %>%
  transmute(Node = To,
            Program = To,
            Partnerships,
            level = 2)

vertices3 <- tibble(
  Node = '',
  Program = NA,
  Partnerships = 0,
  level = 3
)

vertices <- bind_rows(vertices1, vertices2, vertices3) %>%
  mutate(radius = Partnerships ** (1.8),
         # scaling circles
         Program = factor(Program, names(program_colors))) %>%
  arrange(level, Program, Node)

top_programs <- as.character(unique(vertices$Program))

#Several Programs actually participated in other capacity building organizations,
#but I had to change their name because you can't have duplicate nodes.

graph <- graph_from_data_frame(edges, vertices = vertices)

```


```{r, network_formatting}
set.seed(34)
windowsFonts(Georgia=windowsFont("Georgia"))

# create custom layout by updating existing circle layout
layout <- create_layout(graph, layout = 'circle')


outer_circle <- layout %>%
  dplyr::filter(level == 1) %>%
  dplyr::mutate(Program = factor(Program, names(program_colors))) %>%
  dplyr::arrange(Program, desc(name)) %>%
  dplyr::mutate(
    x = cos((row_number() - 1) / number_of_nonprofits * 2 * pi),
    y = sin((row_number() - 1) / number_of_nonprofits * 2 * pi)
  )


# positioning circle centers manually by specifying polar coords
angles <- c(43, 100, 110, 115, 135, 190, 315, 0)
radii <- c(0.65, 0.3, 0.6, 0.8, 0.65, 0.52, 0.45,0)
centers <- tibble(
  x = radii * cos(angles / 180 * pi),
  y = radii * sin(angles / 180 * pi)
)
inner_circle <- bind_cols(centers, select(filter(layout, level != 1), -x, -y))


layout[] <- dplyr::bind_rows(outer_circle, inner_circle) 
layout$x[layout$name == "Capital IDEA"] <- 0.68068502
layout$y[layout$name == "Capital IDEA"] <- -7.325762e-01
layout$x[layout$name == "Health Alliance for Austin Musicians"] <- 0.97254101
layout$y[layout$name == "Health Alliance for Austin Musicians"] <- -2.327316e-01
layout$x[layout$name == "Literacy Coalition"] <- 0.68068502
layout$y[layout$name == "Capital IDEA"] <- -7.325762e-01

layout$x[layout$name == "YouthWorks"] <- -0.65888581
layout$y[layout$name == "YouthWorks"] <- -7.522430e-01
layout$x[layout$name == "Any Baby Can"] <- -0.96528968
layout$y[layout$name == "Any Baby Can"] <- 2.611816e-01
layout <- dplyr::arrange(layout, .ggraph.index)




ggraph(layout) +
  geom_edge_diagonal(
    aes(edge_color = node1.Program, edge_alpha = as.factor(Main)),
    edge_width = 0.3, show.legend = FALSE
  ) +
  geom_node_point(
    aes(size = radius, color = Program),
    alpha = 0.6, show.legend = FALSE
  ) +
  scale_edge_color_manual(values = program_colors) +
  scale_color_manual(values = program_colors) +
  scale_size_area(max_size = 150) +
  scale_edge_alpha_manual(values = c(0.6, 1)) +
  coord_fixed() +
  labs(
    title = 'Data Capacity Building Organizations in Central Texas',
    subtitle = 'and their Nonprofit Connections'
  ) +
    geom_node_text(#American youthworks changed to youthworks, Texas Homeless Network to THN, Literacy Coalition of Central Texas changed to Literacy Coalition, Workforce Solutions - Capital Area Workforce Board changed to wfs, Learn All the Time == LATT 
     aes(
       x = 1.0175 * x,
       y = 1.0175 * y,
       label = ifelse(
         Partnerships > 2, 
         name, 
         ""),
       angle = -((-node_angle(x, y) + 90) %% 180) + 90,
       filter = !(name %in% top_programs)
     ),
     size = 4, hjust = 'outward', family = 'Georgia'
   ) +
  geom_node_text(
    aes(
      x = x,
      y = y ,
      label = ifelse(
        Partnerships > 2,
        format(Partnerships, big.mark = ','),
        ""
      ),
      angle = -((-node_angle(x, y) + 90) %% 180) + 90,
      filter = !(name %in% top_programs)
    ),
    size = 4, hjust = 0.5, family = 'Georgia'
  ) +
  geom_node_text(
    aes(
      x = x,
      y = y,
      label = name,
      filter = name %in% top_programs
    ),
    size = 6, hjust = 0.5, family = 'Georgia'
  ) +
  geom_node_text(
    aes(
      x = x,
      y = y - 0.045,
      label = ifelse(
        Partnerships > 5,
        format(Partnerships, big.mark = ','),
        Partnerships
      ),
      filter = name %in% top_programs
    ),
    size = 5, hjust = 0.5, family = 'Georgia'
  ) +
  theme_void() +
  theme(
    text = element_text(family = 'Georgia'),
    legend.position = c(0.645, 0.51),
    plot.title = element_text(
      face = 'bold', hjust = 0.5, size = 20, margin = margin(t = 45, b = 3)
    ),
    plot.subtitle = element_text(
      face = 'plain', hjust = 0.5, size = 18, margin = margin(t = 5, b = 3)),
    plot.margin = margin(0,0,0,0)
  )

ggsave(
  'images/nonprofit_network.png',
  width = 12, height = 12.5, dpi = 500
)
```
