---
title: "Network Analysis Tutorial with igraph"
author: "Ethan Tenison"
date: "7/12/2020"
output: html_document
---

```{r example_1}

library(igraph)
library(readr)
set.seed(27)

nodes <- read_csv("Network Analysis Tutorial/Dataset1-Media-Example-NODES.csv")
links <- read_csv("Network Analysis Tutorial/Dataset1-Media-Example-EDGES.csv")

head(nodes)

head(links)

nrow(nodes); length(unique(nodes$id))

nrow(links); nrow(unique(links[,c("from", "to")]))

links <- aggregate(links[,3], links[,-3], sum)

links <- links[order(links$from, links$to),]

colnames(links)[4] <- "weight"

rownames(links) <- NULL

net <- graph_from_data_frame(d=links, vertices=nodes, directed=T) 

class(net)

print(plot(net, edge.arrow.size=.4,vertex.label=NA))
net <- simplify(net, remove.multiple = F, remove.loops = T)
print(plot(net, edge.arrow.size=.4,vertex.label=NA))
```


```{r example_2}
nodes2 <- read.csv("Network Analysis Tutorial/Dataset2-Media-User-Example-NODES.csv", header=T, as.is=T)

links2 <- read.csv("Network Analysis Tutorial/Dataset2-Media-User-Example-EDGES.csv", header=T, row.names=1)

links2 <- as.matrix(links2)

dim(links2)

dim(nodes2)

net2 <- graph_from_incidence_matrix(links2)

table(V(net2)$type)

net2.bp <- bipartite.projection(net2)

as_incidence_matrix(net2)  %*% t(as_incidence_matrix(net2)) 

t(as_incidence_matrix(net2)) %*%   as_incidence_matrix(net2)

print(plot(net2.bp$proj1, vertex.label.color="black", vertex.label.dist=1,

vertex.size=7, vertex.label=nodes2$media[!is.na(nodes2$media.type)]))

(plot(net2.bp$proj2, vertex.label.color="black", vertex.label.dist=1,

     vertex.size=7, vertex.label=nodes2$media[ is.na(nodes2$media.type)]))
```