---
title: "CONNECT Fall 2021 Cohort Report"
description: | 
  Analyzing the results from organizations and students at UT Austin, UT Dallas, and the University of Houston
author: Ethan Tenison 
affiliation: RGK Center for Philanthropy and Community Service 
date: "`r format(Sys.Date(), '%B %d, %Y') `"
output:
  html_document:
    code_folding: hide
    theme:
      bg: "#f2f0ec"
      fg: "#000000"
      primary: "#33638D"
      base_font:
        google: "Prompt"
      code_font:
        google: "JetBrains Mono"
---
Analyzing the results from organizations and students at UT Austin, UT Dallas, and the University of Houston. 

```{r setup, include=FALSE, message=FALSE, warning=FALSE, fig.align = 'center'}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

library(tidyverse)
library(qualtRics)
library(bslib)
library(RColorBrewer)
library(extrafont)
library(viridis)
library(hrbrthemes)
library(patchwork)
library(scales)
loadfonts(device = "win")
```


```{r qualtrics, message=FALSE, warning=FALSE, echo=TRUE, results='hide', include = FALSE}

# # Connecting to the Qualtrics API
# qualtrics_api_credentials(
# api_key = "", 
# base_url = "ca1.qualtrics.com", 
# install = TRUE,
# overwrite = TRUE
# )

#Pulling the organization and students surveys 
surveys <- all_surveys() 

#Finding the row index for organization and student surveys
stu_number <- which(surveys$name=="01.Student Close-Out Survey_Fall 2021", arr.ind=TRUE)
org_number <- which(surveys$name=="01.Organization Close-out Survey_Fall 2021", arr.ind=TRUE)

#Fetching the Survey Contents 
org_raw <- fetch_survey(surveyID = surveys$id[org_number], force_request = TRUE)
stu_raw <- fetch_survey(surveyID = surveys$id[stu_number], force_request = TRUE)

#write.csv(stu_raw, "data/interim/student_data_fall2021.csv", row.names = FALSE)


```

# Organizations

### Net Promoter Score 

```{r netpromoter, include = FALSE}


 prom <- org_raw |> 
   group_by(Q3_NPS_GROUP) |> 
   count() |> 
   filter(!is.na(Q3_NPS_GROUP))
 
 
 # Compute percentages
 prom$fraction <- prom$n / sum(prom$n)
 
 # Compute the cumulative percentages (top of each rectangle)
 prom$ymax <- cumsum(prom$fraction)
 
 # Compute the bottom of each rectangle
 prom$ymin <- c(0, head(prom$ymax, n=-1))
 
 # Compute label position
 prom$labelPosition <- (prom$ymax + prom$ymin) / 2
 
 # Compute a good label
 prom$label <- paste0(prom$Q3_NPS_GROUP, ": \n", prom$n)
 
 theme_set(theme_classic())
 # Make the plot
 prom <- ggplot(prom, aes(ymax=ymax, ymin=ymin, xmax=4, xmin=3, fill=Q3_NPS_GROUP)) +
   geom_rect() +
   geom_label( x=3.5, aes(y=labelPosition, label=label), size=4, alpha = 0, label.size = NA,
               label.padding = unit(0.05, "lines")) +
   labs(caption= "Organizations") +
   scale_fill_manual(values = c("#ffbf00", "#007000")) +
   coord_polar(theta="y") +
   xlim(c(2, 4)) +
   theme_void() +
   theme(legend.position = "none",
         plot.caption = element_text(size = 20, hjust = 0.5))

 color = alpha('black', .5)
# ggsave("reports/2021_fall/org_promoter_score.png")

prom
```

### Organization Learning 

```{r learning}


lrn <- org_raw |>
  select(starts_with("Q9")) |>
  pivot_longer(
    cols = Q9_1:Q9_4,
    names_to = "bucket",
    values_to = "response"
  ) |> 
  filter(!is.na(response)) |> 
  group_by(bucket, response) |> 
  count() |> 
  mutate(bucket = case_when(
         bucket == "Q9_1" ~ "Measurement",
         bucket == "Q9_2" ~ "Data Collection",
         bucket == "Q9_3" ~ "Data Analysis",
         bucket == "Q9_4" ~ "Advanced\n Analytics")
         )

theme_set(theme_classic())
ggplot(lrn, aes(fill=response, y=n, x=reorder(bucket, -n))) + 
    geom_bar(position="stack", stat="identity") +
    scale_fill_viridis(discrete = T) +
    labs(
      title = "Participation in this program helped my organization learn how to...",
      y = "Number", 
      x = "",
      fill = ""
    ) +
  theme(text = element_text(size =14))

ggsave("reports/2021_fall/org_learning.png")

```

### Table of New Organizations

```{r table}

library(gt)

new_org <- org_raw |>
  select(Q2, Q13) |>
  filter(!is.na(Q13)) |>
  rename(Organization = "Q2",
         Recomentation = "Q13")

new_org[1, 2] <- "Center for Health Communication at UT"
new_org[2, 2] <- "Local fast-growing churches"

gt_org <- new_org |>
  gt() |>
  tab_header(title = "Possible Leads") |> tab_style(style = list(
    cell_text(
      size = px(28),
      weight = "normal",
      align = "left",
    )
  ),
  locations = list(cells_title(groups = "title"))) |> 
  tab_style(
  style = list( 
   cell_text(
    size = px(24),
    color = "#000000",
   )
  ),
  locations = list(
   cells_column_labels(everything())
  )
 )

gt_org
```

### Org Clients

```{r org_dei}
library(Hmisc) 

clients_raw <- org_raw |>
  select(starts_with("Q24"))

clients <- clients_raw |>
  select(starts_with("Q24")) |>
  pivot_longer(Q24_2:Q24_6, names_to = "Race", values_to = "Percent") |>
  filter(!is.na(Percent)) |>
  group_by(Race) |>
  dplyr::summarize(average = mean(Percent)) |>
  mutate(
    Race = case_when(
      Race == "Q24_2" ~ "Asian",
      Race == "Q24_7" ~ "Black",
      Race == "Q24_8" ~ "Hispanic",
      Race == "Q24_10" ~ "Native American/\n Pacific Islander",
      Race == "Q24_6" ~ "White"
    )
  )

theme_set(theme_classic())
org_clients <- ggplot(clients, aes(fill=Race, y=average, x=reorder(Race, -average))) + 
    geom_bar(stat="identity") +
    scale_fill_viridis(discrete = T) +
    labs(
      title = "Clients",
      y = "Average Percent", 
      x = "",
      fill = ""
    ) +
  theme(legend.position = "none",
        text = element_text(size =14)) 

ggsave("reports/2021_fall/org_clients.png")



```


### Org Board

```{r org_dei2}
library(Hmisc) 

board_raw <- org_raw |>
  select(starts_with("Q28"))

board <- board_raw |>
  pivot_longer(Q28_2:Q28_6, names_to = "Race", values_to = "Percent") |>
  filter(!is.na(Percent)) |>
  group_by(Race) |>
  dplyr::summarize(average = mean(Percent)) |>
  mutate(
    Race = case_when(
      Race == "Q28_2" ~ "Asian",
      Race == "Q28_7" ~ "Black",
      Race == "Q28_8" ~ "Hispanic",
      Race == "Q28_10" ~ "Native American/\n Pacific Islander",
      Race == "Q28_6" ~ "White"
    )
  )

theme_set(theme_classic())
org_board <- ggplot(board, aes(fill=Race, y=average, x=reorder(Race, -average))) + 
    geom_bar(stat="identity") +
    scale_fill_viridis(discrete = T) +
    labs(
      title = "Board of directors",
      y = "", 
      x = "",
      fill = ""
    ) +
  theme(legend.position = "none",
        text = element_text(size =14))


```


### Demo Combined

```{r demo_combined}

demo_org <-
  org_clients + org_board + plot_annotation(
    title = "Social Identities accross Organizations",
    caption = "*These are only averages of estimates. More data needs to be collected.",
    theme = theme(plot.title = element_text(size = 20))
  ) + plot_layout(widths = c(1.5, 1))

demo_org

ggsave("reports/2021_fall/org_demographics.png", width = 9, height = 4.5)

```


# Student Data

### Net Promoter Score

```{r netpromoter_stu}


 proms <- stu_raw |> 
   group_by(Q4_NPS_GROUP) |> 
   count() |> 
   filter(!is.na(Q4_NPS_GROUP))
 
 
 # Compute percentages
 proms$fraction <- proms$n / sum(proms$n)
 
 # Compute the cumulative percentages (top of each rectangle)
 proms$ymax <- cumsum(proms$fraction)
 
 # Compute the bottom of each rectangle
 proms$ymin <- c(0, head(proms$ymax, n=-1))
 
 # Compute label position
 proms$labelPosition <- (proms$ymax + proms$ymin) / 2
 
 # Compute a good label
 proms$label <- paste0(proms$Q4_NPS_GROUP, ": \n", proms$n)
 
 # Make the plot
prom_stu <- ggplot(proms, aes(ymax=ymax, ymin=ymin, xmax=4, xmin=3,
                              fill=Q4_NPS_GROUP)) +
   geom_rect() +
   geom_label( x=3.5, aes(y=labelPosition, label=label),alpha = 0, size=4,
               label.size = NA,
               label.padding = unit(0.05, "lines")) +
   scale_fill_manual(values = c("#D2222D", "#ffbf00", "#007000")) +
   coord_polar(theta="y") +
   xlim(c(2, 4)) +
   labs(caption = "Students") +
   theme_void() +
   theme(legend.position = "none",
         plot.caption = element_text(size = 20, hjust = 0.5))

prom_stu

```

### Improvements


```{r improvements}

library(wordcloud)
library(RColorBrewer)
library(tm) # to create corpus
library(wordcloud2)
library(htmlwidgets)

# Create a vector containing only the text
text <- stu_raw$Q11

# Create a corpus
docs <- Corpus(VectorSource(text))

# standardize corpus
docs <- docs %>%
  tm_map(removeNumbers) %>%
  tm_map(removePunctuation) %>%
  tm_map(stripWhitespace)
docs <- tm_map(docs, content_transformer(tolower))
docs <- tm_map(docs, removeWords, stopwords("english"))

# create a document matrix
dtm <- TermDocumentMatrix(docs)
matrix <- as.matrix(dtm)
words <- sort(rowSums(matrix), decreasing = TRUE)
df <- data.frame(word = names(words), freq = words)
df$word <- as.character(df$word)
df <- df |> 
  mutate(freq = case_when(
         word == "workshop" ~ 7,
         TRUE ~ freq)) |> 
  filter(word != "workshops")
  target <- c("also", "project", "really", "helpful", "wasnt", "etc", "asks", "move", "gave", "connect", "fellows", "program")
  "%ni%" <- Negate("%in%")
  df <- filter(df, word %ni% target)
df$word <- as.factor(df$word)

set.seed(27)
wordcloud(words = df$word,
            freq = df$freq, 
            min.freq = 1, 
            rot.per= 0.4,
            colors = viridis(8),
            random.order = FALSE,
            family = "serif", font = 2)


```


### Usefulness 

```{r useful}


useful <- stu_raw |>
  select(starts_with("Q13")) |> 
  pivot_longer(Q13_1:Q13_5, names_to = "question", values_to = "usefullness") |> 
  filter(!is.na(usefullness)) |> 
  group_by(usefullness) |> 
  count()


theme_set(theme_classic())
ggplot(useful, aes(fill=usefullness, y=n, x=reorder(usefullness, n))) + 
    geom_bar(stat="identity") +
    scale_fill_viridis(discrete = T) +
    coord_flip() +
    labs(
      title = "What resources did you find most helpful for your\n learning and/or completing your client project?",
      y = "Total Number", 
      x = "",
      fill = ""
    ) +
  theme(legend.position = "none")


```

### Usefullness by bucket 


```{r use_bucket}

use_bucket <- read_csv("data/processed/student_data_fall2021_addbucket.csv") |> 
  select(Q2, Project_Bucket, starts_with("Q13")) |> 
  mutate(Project_Bucket = case_when(
    Project_Bucket == "Measurement Strategy" ~ "Measurement & Collection",
    Project_Bucket == "Measurement Strategy, Data Collection & Tool Development" ~ "Measurement & Collection",
    Project_Bucket == "Data Collection & Tool Development" ~ "Measurement & Collection",
    Project_Bucket == "Data Interpretation & Analysis" ~ "Data Intensive",
    Project_Bucket == "Advanced Analytics & Business Intelligence" ~ "Data Intensive",
    Project_Bucket == "Data Collection & Tool Development, Data Interpretation & Analysis" ~ "Data Intensive"
    
  )) |> 
  filter(!is.na(Project_Bucket)) |> 
  pivot_longer(Q13_1:Q13_5, names_to = "question", values_to = "usefullness") |> 
  filter(!is.na(usefullness)) |> 
  group_by(Project_Bucket, usefullness) |> 
  count() |> 
  mutate(perc = case_when(
    Project_Bucket == "Data Intensive" ~ n/4,
    Project_Bucket == "Measurement & Collection" ~ n/8
  ))

# data intensive = 4, measurement = 8

library(scales)

theme_set(theme_classic())
ggplot(use_bucket, aes(fill=usefullness, y=perc, x=reorder(usefullness, perc))) + 
    geom_bar(stat="identity") +
    scale_fill_viridis(discrete = T) +
    coord_flip() +
    labs(
      title = "What resources did you find most helpful for your\n learning and/or completing your client project?",
      subtitle = "By Bucket Type",
      y = "Percent", 
      x = "",
      fill = ""
    ) +
  #scale_y_continuous(labels = scales::percent(100, scale = 1)) +
  facet_wrap(~Project_Bucket) +
  theme(legend.position = "none")



```


### Diversity 

```{r diversity}

div <- stu_raw |> 
  select(Q23) |> 
  group_by(Q23) |> 
  count() 

div <- div[1:4,1:2]

theme_set(theme_classic())
ggplot(div, aes(fill=Q23, y=n, x=reorder(Q23, n))) + 
    geom_bar(stat="identity") +
    scale_fill_viridis(discrete = T) +
    coord_flip() +
    labs(
      title = "On a scale of 1 through 5, how diverse would you rate\n the folx you interacted with during your time in the CONNECT\n Program (ie. students, staff, agencies)?",
      y = "Total Number", 
      x = "",
      fill = ""
    ) +
  theme(legend.position = "none")

```


### Race

```{r race}

race <- stu_raw |> 
  select(starts_with("Q18")) |> 
  pivot_longer(Q18_1:Q18_9, names_to = "Q18", values_to = "race") |> 
  filter(!is.na(race)) |> 
  group_by(race) |> 
  count()
  
  

theme_set(theme_classic())
ggplot(race, aes(fill=race, y=n, x=reorder(race, n))) + 
    geom_bar(stat="identity") +
    scale_fill_viridis(discrete = T) +
    coord_flip() +
    labs(
      title = "Which of the following best describes your race/ethnicity?",
      y = "Total Number", 
      x = "",
      fill = ""
    ) +
  theme(legend.position = "none")




```



# Combined

```{r net_com}

prom_combined = prom + prom_stu +
  plot_annotation(title = "Net Promoter Score", subtitle= "NPS measures how likely particpants are to recommend CONNECT", theme = theme(plot.title = element_text(size = 20))) 

ggsave("reports/2021_fall/netpromoter_combined.png")

```

